### ISSUE TITLE
Randomized benchmarking protocol raises `KeyError` when fit fails

### ISSUE THREAD

**Issue by lriesebos** [pyGSTio/pyGSTi#217]
**Describe the bug**

When using `pygsti.protocols.RandomizedBenchmarking().run()` on randomized data and the fit fails (e.g. all data is zero), an unexpected `KeyError` is raised.

```
ERROR:worker(297,pygsti_new.py):root:Terminating with exception (KeyError: 'a')
Traceback (most recent call last):
  File "/home/leon/projects/staq/repository/circuit/pygsti_new.py", line 382, in analyze
    results = protocol.run(protocol_data)
  File "/nix/store/31s7rqz2c32vgv2gn8c3k2iq0v1drdds-python3-3.8.11-env/lib/python3.8/site-packages/pygsti/protocols/rb.py", line 974, in run
    bs_ff_results, bs_faf_results = _get_rb_fits(bootstrap_cache[self.datatype])
  File "/nix/store/31s7rqz2c32vgv2gn8c3k2iq0v1drdds-python3-3.8.11-env/lib/python3.8/site-packages/pygsti/protocols/rb.py", line 950, in _get_rb_fits
    full_fit_results, fixed_asym_fit_results = _rbfit.std_least_squares_fit(
  File "/nix/store/31s7rqz2c32vgv2gn8c3k2iq0v1drdds-python3-3.8.11-env/lib/python3.8/site-packages/pygsti/algorithms/rbfit.py", line 196, in std_least_squares_fit
    seed_full = [FAF_results['estimates']['a'], FAF_results['estimates']['b'], FAF_results['estimates']['p']]
KeyError: 'a'
```

**To Reproduce**

Probably you can use [pygsti_all_zero.zip](https://github.com/pyGSTio/pyGSTi/files/7455382/pygsti_all_zero.zip) to create a `pygsti.protocols.ProtocolData` object. Then call `pygsti.protocols.RandomizedBenchmarking().run()` and provide the protocol data object as the argument.

**Expected behavior**

Probably a better error message or something similar would do.

**Environment (please complete the following information):**

 - pyGSTi version 0.9.10
 - python version 3.8
 - Ubuntu 20.04

**Comment by enielse** [comment]
Fixed in e4bac3c0744e651f68ac6c3e1ae7cf8ea8a09881.  The error: `"Initial fixed-asymptotic RB fit failed and is needed to seed requested full+FA fit type. Please check that your data is valid."` is now raised instead of a `KeyError`, and was verified on the supplied test case.
