### ISSUE TITLE
pygsti cannot run on Windows

### ISSUE THREAD

**Issue by ldes89150** [pyGSTio/pyGSTi#41]
I tried to use pygsti on Windows with anaconda python distribution, and I got the following error. 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\__init__.py", line 12, in <module>
    from . import algorithms as alg
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\algorithms\__init__.py", line 12, in <module>
    from .core import *
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\algorithms\core.py", line 16, in <module>
    from .. import optimize     as _opt
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\optimize\__init__.py", line 12, in <module>
    from .customlm import *
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\optimize\customlm.py", line 14, in <module>
    from ..tools import mpitools as _mpit
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\tools\__init__.py", line 11, in <module>
    from .jamiolkowski import *
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\tools\jamiolkowski.py", line 10, in <module>
    from ..baseobjs.basis import basis_matrices as _basis_matrices
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\baseobjs\__init__.py", line 13, in <module>
    from .profiler import Profiler
  File "C:\MiniConda\envs\IonControl\lib\site-packages\pygsti\baseobjs\profiler.py", line 24, in <module>
    import resource as _resource
ModuleNotFoundError: No module named 'resource'
>>>
```
It seems `resource` module doesn't exist on the Windows platform. Is there a way to use it on a Windows system?

**Comment by ldes89150** [comment]
After I installed `psutil`, I can use `pygsti` now. Is it possible to make `psutil` be one of its dependencies while installing with pip on Windows platform?

**Comment by enielse** [comment]
The `resource` module is usually included as part of the standard Python library (I think as of v2.7 at least?), so it's weird that your anaconda distribution doesn't include it.  PyGSTi doesn't require `psutil`  because it only uses it for memory profiling and can fall back on the (usually always-present) `resource` module if `psutil` isn't there.  This is why your workaround works: if you have the optional `psutil` package then pyGSTi prefers this and `resource` is never needed.  I think it makes sense to leave `psutil` as an optional dependency in pyGSTi, which leaves you with several possible workarounds:

- install a more complete Python for Windows; I've used [Enthought Canopy](https://www.enthought.com/product/canopy/) successfully.
- install pygsti via `pip install pygsti` and install `psutil` separately, as you've mentioned.
- install pygsti with it's optional `psutil` dependency via `pip install pygsti.[accurate memory profiling]` (note: you can also use `.[complete]` which will cause `pip` to install *all* of pyGSTi's optional dependencies).

**Comment by robpkelly** [comment]
I'm closing this issue since the workaround is preferable to other long-term fixes.
